insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('986448713-2', 'Red 2', 'Dutch', 270, 2);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('170945644-2', 'Goodbye, Dragon Inn (Bu san)', 'West Frisian', 364, 3);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('813890630-8', 'Vacuum-Cleaner Salesmen (Pölynimurikauppiaat)', 'Finnish', 163, 4);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('545952023-1', 'Mortel transfert', 'Afrikaans', 440, 4);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('665293857-X', 'Two-Lane Blacktop', 'Malay', 217, 5);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('681409341-3', 'Heroes of Telemark, The ', 'Dzongkha', 489, 5);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('641675360-X', 'Balzac and the Little Chinese Seamstress (Xiao cai feng)', 'Albanian', 159, 5);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('545500682-7', 'Wild Heritage', 'Greek', 498, 5);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('018152242-X', 'Horror Business', 'Dutch', 379, 2);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('816557980-0', 'Big White, The', 'Bengali', 175, 1);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('224474651-8', 'Pepi, Luci, Bom (Pepi, Luci, Bom y Otras Chicas del Montón)', 'Filipino', 326, 4);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('384642242-8', 'Five Senses, The', 'Montenegrin', 323, 3);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('556969237-1', 'Ninja', 'Khmer', 356, 3);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('456339827-6', 'Next Stop Wonderland', 'Macedonian', 115, 2);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('968693721-8', 'Girl from Jones Beach, The', 'Malay', 349, 1);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('094893108-6', 'Uncertainty', 'Arabic', 455, 2);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('342552351-1', 'Coma', 'Arabic', 263, 2);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('720493474-1', 'Ascension', 'Gagauz', 461, 5);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('756675690-7', 'Harvest/La Cosecha, The', 'Māori', 131, 3);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('490025038-4', 'It Is Written in the Stars, Inspector Palmu (Tähdet kertovat, komisario Palmu)', 'Filipino', 421, 2);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('792986556-8', 'Mating Habits of the Earthbound Human, The', 'Bengali', 489, 4);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('743934501-0', 'Dobermann', 'Icelandic', 187, 1);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('540987750-0', 'Black Heaven (L''autre monde) (Other World, The)', 'Hindi', 108, 5);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('557625548-8', 'Legend of Lylah Clare, The', 'Oriya', 408, 5);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('423428624-9', 'Fright', 'Nepali', 266, 2);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('288692425-3', 'Grass Harp, The', 'Marathi', 376, 1);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('315803380-1', 'Rise', 'Hungarian', 241, 4);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('600976932-9', 'Sirens', 'Bosnian', 323, 1);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('826131857-5', 'Trumpet of the Swan, The', 'Haitian Creole', 118, 1);
insert into BOOK (ISBN, TITLE, LANGUAGE, NUMBER_OF_PAGES, NUMBER_OF_COPIES) values ('334025664-0', 'Carless Love', 'Hungarian', 197, 4);